apiVersion: v1
kind: Service
metadata: 
  name: myapp
  labels: 
    name: myapp
  
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector: 
    name: myapp
    version: v1
  type: LoadBalancer
